import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import MainWrapper from "@/components/layout/main-wrapper";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} antialiased bg-black text-white p-7 w-screen overflow-x-hidden select-none`}
      >
        <MainWrapper>{children}</MainWrapper>
      </body>
    </html>
  );
}
